### ISSUE TITLE
more data is need

### ISSUE THREAD

**Issue by AuroraWong** [dlvalencia/WaveClus_Datasets#1]
I found the website where these data could be found can never open. Could you give the new valid website to download the dataset multi-unit dataset.

**Comment by dlvalencia** [comment]
It seems that they've updated their website (now here: https://le.ac.uk/csn/data) and that the multi-unit dataset is not listed. Perhaps you can reach out to their research group to download the data directly. Otherwise, you can download the five parts of the MultiUnit_Dataset and combine them with WinRar.
